# Generated by Django 4.2.9 on 2024-04-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="verfied_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
